spring:
    datasource:
      url: jdbc:mysql://localhost:3306/login-auth
      username: root
      password: Softwareengineer2001@
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

    security:
      jwt:
        secret-key: "my-very-secure-secret-key-that-is-256-bits-long"
        expiration-time: 3600000